name: PR Build and Check

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Maven Build
        run: mvn clean install

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: target/site/
